[ubuntu]
ubuntu-24 ansible_host=192.168.55.101

[windows]
windows-11 ansible_host=192.168.55.102

[rocky]
rocky-10 ansible_host=192.168.55.103

[linux:children]
ubuntu
rocky

[all:vars]
ansible_user=itsm
ansible_ssh_private_key_file=/root/.ssh/id_rsa
ansible_python_interpreter=/usr/bin/python3
ansible_connection=ssh

[windows:vars]
ansible_user=oper
ansible_password=operoper
ansible_connection=winrm
ansible_winrm_server_cert_validation=ignore
ansible_winrm_transport=ntlm
ansible_port=5985